services:
  # --- MySQL Database ---
  db:
    image: mysql:8.0
    container_name: autoparts_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: autoparts_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  # --- Backend (Node + Prisma) ---
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: autoparts_backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql://root:root@db:3306/autoparts_db
      FRONTEND_URL: http://frontend:3000
      API_BASE_URL: http://backend:4000
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/uploads:/app/uploads
    command: >
      sh -c "npx prisma generate &&
             npx prisma migrate deploy &&
             npm run dev"

  # --- Frontend (Next.js) ---
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: autoparts_frontend
    restart: always
    env_file:
      - ./frontend/.env.local
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_BASE: http://localhost:4000/api
      INTERNAL_API_BASE: http://backend:4000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

volumes:
  db_data:
